site_name: echoSMs
nav:
    - Introduction: index.md
    - Benchmarks: benchmark_data.md
    - Contributing: contributing.md
    - API Reference: api_reference.md

theme: readthedocs 

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    docstring_style: numpy
                    show_submodules: false
                    show_symbol_type_heading: true
                    show_bases: true
                    inherited_members: true
                    show_root_heading: true
